const osif = @cImport({
    @cInclude("osif.h");
});

pub const SysCalls = enum(c_uint) {
    CONSOLE_WRITELN = osif.OSIF_SYSCALL_CONSOLE_WRITELN,
    CREATE_PROCESS = osif.OSIF_SYSCALL_CREATE_PROCESS,
    YIELD_PROCESS = osif.OSIF_SYSCALL_YIELD_PROCESS,
    KILL_PROCESS = osif.OSIF_SYSCALL_KILL_PROCESS,
    CONSOLE_SETCOLOR = osif.OSIF_SYSCALL_CONSOLE_SETCOLOR,
    CONSOLE_SETCURSORPOS = osif.OSIF_SYSCALL_CONSOLE_SETCURSORPOS,
    POP_PROCESS_EVENT = osif.OSIF_SYSCALL_POP_PROCESS_EVENT,
    PROCESS_GETPID = osif.OSIF_SYSCALL_PROCESS_GETPID,
    TIMER_GET_TICKCOUNT = osif.OSIF_SYSCALL_TIMER_GET_TICKCOUNT,
    PROCESS_GET_DATAMEM_START = osif.OSIF_SYSCALL_PROCESS_GET_DATAMEM_START,
    WINDOW_CREATE = osif.OSIF_SYSCALL_WINDOW_CREATE,
    WINDOW_DESTORY = osif.OSIF_SYSCALL_WINDOW_DESTORY,
    WINDOW_GET_WINDOW_FB = osif.OSIF_SYSCALL_WINDOW_GET_WINDOW_FB,
    WINDOW_FLUSH_GRAPHICS = osif.OSIF_SYSCALL_WINDOW_FLUSH_GRAPHICS,
    GET_OS_ERROR = osif.OSIF_SYSCALL_GET_OS_ERROR,
    GET_BOOTLOADED_FILE = osif.OSIF_SYSCALL_GET_BOOTLOADED_FILE,
    ABORT_PROCESS = osif.OSIF_SYSCALL_ABORT_PROCESS,
    TEST = osif.OSIF_SYSCALL_TEST,
};

pub const KERNEL_FAILURE: i32 = -1;

pub const KernelError = error.Failure;
