set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CROSSCOMPILE_PATH ~/.local/opt/i686-cross)
set(ARCH x86)

set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_FIND_ROOT_PATH ${CROSSCOMPILE_PATH})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_ASM_NASM_COMPILE_OBJECT "<CMAKE_ASM_NASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")
set(CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS ${CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS} s S)

find_program(
    CROSS_OBJCOPY
    NAMES i686-elf-objcopy
    PATHS ${CROSSCOMPILE_PATH}
    REQUIRED)

find_program(
    CROSS_OBJDUMP
    NAMES i686-elf-objdump
    PATHS ${CROSSCOMPILE_PATH}
    REQUIRED)
