set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CROSSCOMPILE_PATH ~/.local/opt/i686-cross)

set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_FIND_ROOT_PATH ${CROSSCOMPILE_PATH})
set(CMAKE_SYSROOT ${CROSSCOMPILE_PATH})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(CROSS_OBJDIR NAMES i686-elf-objcopy PATHS ${CROSSCOMPILE_PATH})
