# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Unittests build and run

on: [push]

jobs:
  builld_and_test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install nasm gcc-multilib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DMOS_DEBUG_LEVEL="3" -DMARCH="pc" -DARCH="x86"

    - name: Build and run
      run: cmake --build ${{github.workspace}}/build --target run

      #- name: Test
      #  working-directory: ${{github.workspace}}/build
      #  run: cmake --build . --target run |grep -c FAIL > /dev/null; test $? -eq 1
